#!/usr/bin/bash

SUPERUSER_COMMAND=""

if [[ $EUID -ne 0 ]]; then
    SUPERUSER_COMMAND="sudo"
fi

print_usage() {
    echo "Usage: $0 <source_directory> <cache-key>"
    echo "Example: $0 /path/to/source_dir source_dir-cache-key"
    exit 1
}

echo "Cache Saver v0.1"

if [ $# -lt 2 ]; then
    print_usage
fi

original_dir="$(pwd)"

source_dir="$1"
dest_path="/mnt/cache/$2.tar.gz"
dest_file="$(basename $dest_path)"


if [ ! -d "$source_dir" ]; then
    echo "Error: '$source_dir' is not a valid directory."
    print_usage
fi

parent_dir="$(dirname $source_dir)"
base_dir="$(basename $source_dir)"

cd "$parent_dir" || { echo "Error: Cannot change to parent directory"; exit 1; }

# if the destination exists, remove it as it's about to be replaced.
if [ -f "$dest_path" ]; then
    $SUPERUSER_COMMAND rm -rf "$dest_path"
fi

# $SUPERUSER_COMMAND tar -zcf "$dest_file" --preserve-permissions "$base_dir" || { echo "Error: Failed to create cache archive."; exit 1; }
# $SUPERUSER_COMMAND mv "$dest_file" "$dest_path" || { echo "Error: Failed to move archive to cache location."; exit 1; }

$SUPERUSER_COMMAND tar -zcf "$dest_path" --preserve-permissions "$base_dir" || { echo "Error: Failed to create cache archive."; exit 1; }

cd "$original_dir"
