#!/usr/bin/bash

SUPERUSER_COMMAND=""

if [[ $EUID -ne 0 ]]; then
    SUPERUSER_COMMAND="sudo"
fi

print_usage() {
    echo "Usage: $0 <cache-key> <destination_directory"
    echo "Example: $0 cache-key /path/to/dest_dir"
    exit 1
}

echo "Cache Loader v0.1"

if [ $# -lt 2 ]; then
    print_usage
fi

original_dir="$(pwd)"

source_tarball="/mnt/cache/$1.tar"
dest_dir="$2"

if [ ! -d "$dest_dir" ]; then
    echo "Error: Destination '$dest_dir' does not exist."
    print_usage
fi

if [ ! -f "$source_tarball" ]; then
    echo "Cache miss."
    exit
fi

echo "Cache hit."

cd "$dest_dir"

$SUPERUSER_COMMAND tar -xf -I pigz "$source_tarball"

cd "$original_dir"
